# Customer Success KPIs

In [19]:
import sys
sys.path.append('../')
import conexion_database

# Limpieza de query
from clean_query import clean_query

No Laptop Tandamos
Spartan PC

In [1]:
import pandas as pd
import numpy as np
pd.options.display.max_columns = None

# Para guardar los archivos con la fecha de hoy
from datetime import datetime, date, timedelta

# La función de weeknum es equivalente a la de WEEKNUM en Excel, modo 1, en la que se basa Alejo
from calweek import weeknum

In [2]:
# Conexión con Google Sheets
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import json

scopes = [
'https://www.googleapis.com/auth/spreadsheets',
'https://www.googleapis.com/auth/drive'
]
credentials = ServiceAccountCredentials.from_json_keyfile_name("../gsheets_key.json", scopes) #access the json key you downloaded earlier 
client = gspread.authorize(credentials) # authenticate the JSON key with gspread

In [3]:
df = pd.read_excel('Data_Customer_Success/Issues.xlsx')
df.head()

C:\ProgramData\Anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,Issue Id,Project,Tags,Summary,Reporter,Created,Updated,Resolved,Priority,Type,State,Assignee,Subsystem,Fix versions,Affected versions,Fixed in build,Estimation,Spent time,Estimated Dates,App User ID,Subtype,Description,Votes
0,CS-508,Customer Service,NaN,Pago o unitanda,Tandamos Administrator,2022-05-02 15:18:32.517,2022-05-02 15:18:32.517,NaT,Normal,0. Sin Categorizar,Open,Unassigned,No Subsystem,Unscheduled,Unknown,Next Build,NaN,NaN,NaN,19206.0,0.0 Sin Categorizar,"Cancelación de mi primera unitanda, en espera ...",0.0
1,CS-507,Customer Service,NaN,Pago o unitanda ayuda-activado,Tandamos Administrator,2022-05-02 11:11:20.512,2022-05-02 12:34:32.047,2022-05-02 12:34:31.919,Normal,3. Dudas con mi Unitanda/SC,Resolved,Unassigned,No Subsystem,Unscheduled,Unknown,Next Build,NaN,NaN,NaN,19498.0,3.3 Adelantar Pagos,Para otro tanda solo me queda 1 pago,0.0
2,CS-505,Customer Service,NaN,Pago o unitanda ayuda-tanda,Tandamos Administrator,2022-05-01 23:35:17.373,2022-05-02 12:31:13.729,2022-05-02 12:31:13.596,Normal,1. Cómo funciona?,Resolved,Unassigned,No Subsystem,Unscheduled,Unknown,Next Build,NaN,NaN,NaN,23876.0,1.1 Saber de Tandamos,Solo requiero explicación de como funciona,0.0
3,CS-503,Customer Service,NaN,Otro ayuda-generico,Tandamos Administrator,2022-04-29 18:36:30.378,2022-05-02 12:27:45.232,NaT,Normal,5. Pagos/Transferencias,In Progress,Unassigned,No Subsystem,Unscheduled,Unknown,Next Build,NaN,NaN,NaN,11962.0,0.0 Sin Categorizar,"Tengo un adeudo con ustedes, el motivo fue po...",0.0
4,CS-500,Customer Service,NaN,Pago o unitanda ayuda-sin-afiliar,Tandamos Administrator,2022-04-28 23:29:42.280,2022-05-02 12:17:37.978,NaT,Normal,4. Validación de identidad,In Progress,Unassigned,No Subsystem,Unscheduled,Unknown,Next Build,NaN,NaN,NaN,7583.0,7.1 Otras Consultas,__file__,0.0

## Data

### Data tau

In [20]:
# Redactar SQL query
query = """
SELECT tau.id, name, email, phone, signup_cohort_date
FROM tdm_app_user tau 
WHERE tau.id NOT IN (7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 41, 90, 188, 369, 636, 929, 1574, 1788, 2394, 2440, 2432, 2442, 2443, 2444, 2445, 2447, 2446, 2450, 2451, 2452,  2454, 2455, 2477, 3227, 4773, 4776, 4816, 7572, 12912, 13697, 19651)
;
"""
query = clean_query(query)
print(query)

SELECT tau.id, name, email, phone, signup_cohort_date FROM tdm_app_user tau WHERE tau.id NOT IN (7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 41, 90, 188, 369, 636, 929, 1574, 1788, 2394, 2440, 2432, 2442, 2443, 2444, 2445, 2447, 2446, 2450, 2451, 2452, 2454, 2455, 2477, 3227, 4773, 4776, 4816, 7572, 12912, 13697, 19651) ;

In [ ]:
# Cargar query a un DataFrame
df_tau = pd.read_sql_query(query, conexion_database.engine)
print(df_tau.shape)
df_tau.head(4)

## Issue Resolution Time

### Preparar data

In [4]:
data = df[['Issue Id', 'Type', 'Created', 'Resolved', 'State', 'App User ID']].copy()
data.head()

,Issue Id,Type,Created,Resolved,State,App User ID
0,CS-508,0. Sin Categorizar,2022-05-02 15:18:32.517,NaT,Open,19206.0
1,CS-507,3. Dudas con mi Unitanda/SC,2022-05-02 11:11:20.512,2022-05-02 12:34:31.919,Resolved,19498.0
2,CS-505,1. Cómo funciona?,2022-05-01 23:35:17.373,2022-05-02 12:31:13.596,Resolved,23876.0
3,CS-503,5. Pagos/Transferencias,2022-04-29 18:36:30.378,NaT,In Progress,11962.0
4,CS-500,4. Validación de identidad,2022-04-28 23:29:42.280,NaT,In Progress,7583.0

In [5]:
# Agregar columna con tiempo de resolución
data['resolve_time_hrs'] = round(((data.Resolved - data.Created).dt.total_seconds() / 60 / 60), 2)

In [6]:
# Agregar columna con fecha sin los segundos
data['fecha_creacion'] = data.Created.dt.strftime("%Y-%m-%d")
data['fecha_resolucion'] = data.Resolved.dt.strftime("%Y-%m-%d")

In [7]:
data.tail()

,Issue Id,Type,Created,Resolved,State,App User ID,resolve_time_hrs,fecha_creacion,fecha_resolucion
447,CS-86,2. Código,2022-01-09 15:55:16.289,2022-02-04 15:22:22.365,Resolved,7054.0,623.45,2022-01-09,2022-02-04
448,CS-393,2. Código,2022-03-24 09:35:12.666,2022-03-24 17:50:10.116,Resolved,20703.0,8.25,2022-03-24,2022-03-24
449,CS-486,2. Código,2022-04-23 23:35:35.323,2022-04-25 10:07:34.792,Resolved,23362.0,34.53,2022-04-23,2022-04-25
450,CS-436,7. Otros,2022-04-07 01:45:45.793,2022-04-26 19:38:24.398,Resolved,21942.0,473.88,2022-04-07,2022-04-26
451,CS-70,2. Código,2022-01-07 09:59:18.405,2022-04-25 21:25:40.640,Resolved,0.0,2603.44,2022-01-07,2022-04-25

In [8]:
data.columns

Index(['Issue Id', 'Type', 'Created', 'Resolved', 'State', 'App User ID',
       'resolve_time_hrs', 'fecha_creacion', 'fecha_resolucion'],
      dtype='object')

### Pasar a G Sheets

In [9]:
data_f = data[['Issue Id', 'App User ID', 'Type', 'fecha_creacion',
       'fecha_resolucion', 'State', 'resolve_time_hrs']].copy()

# Sustituir NaNs, porque JSON no los acepta
data_f = data_f.fillna('')

In [10]:
sheet = client.open("Business_Health_Dashboard")  #open sheet

#replace sheet_name with the name that corresponds to yours, e.g, it can be sheet1
sheet = sheet.worksheet("data_issues")

In [11]:
sheet.update([data_f.columns.values.tolist()] + data_f.values.tolist(), value_input_option='USER_ENTERED')

{'spreadsheetId': '1ZKpgLgKOSt-8JuokkfHOcTBAG72ER73-RcE-g7sttJ4',
 'updatedRange': 'data_issues!A1:G453',
 'updatedRows': 453,
 'updatedColumns': 7,
 'updatedCells': 3171}

## Gráfica - Tiempo promedio de solución de tickets por semana (hr)

### Preparar data

In [12]:
# Filtrar solo por tickets que ya fueron completados
data_resolucion_promedio = data_f[data_f.State == 'Resolved'].copy()

In [13]:
metricas_por_dia = pd.DataFrame({'dia': pd.date_range(start='2022-01-03', end=date.today().strftime('%Y-%m-%d')),
                           })
metricas_por_dia.head()

         dia
0 2022-01-03
1 2022-01-04
2 2022-01-05
3 2022-01-06
4 2022-01-07

In [14]:
# Corregir tipo de data en las columnas
data_resolucion_promedio['fecha_creacion'] = pd.to_datetime(data_resolucion_promedio['fecha_creacion'], format = "%Y-%m-%d %H:%M:%S")
data_resolucion_promedio['resolve_time_hrs'] = data_resolucion_promedio['resolve_time_hrs'].astype('float')

In [15]:
data_resolucion_promedio

,Issue Id,App User ID,Type,fecha_creacion,fecha_resolucion,State,resolve_time_hrs
1,CS-507,19498.0,3. Dudas con mi Unitanda/SC,2022-05-02,2022-05-02,Resolved,1.39
2,CS-505,23876.0,1. Cómo funciona?,2022-05-01,2022-05-02,Resolved,12.93
5,CS-493,19126.0,4. Validación de identidad,2022-04-27,2022-05-02,Resolved,123.89
6,CS-506,19126.0,4. Validación de identidad,2022-05-02,2022-05-02,Resolved,4.28
7,CS-501,22123.0,4. Validación de identidad,2022-04-29,2022-05-02,Resolved,77.87
...,...,...,...,...,...,...,...
447,CS-86,7054.0,2. Código,2022-01-09,2022-02-04,Resolved,623.45
448,CS-393,20703.0,2. Código,2022-03-24,2022-03-24,Resolved,8.25
449,CS-486,23362.0,2. Código,2022-04-23,2022-04-25,Resolved,34.53
450,CS-436,21942.0,7. Otros,2022-04-07,2022-04-26,Resolved,473.88
451,CS-70,0.0,2. Código,2022-01-07,2022-04-25,Resolved,2603.44

In [16]:
# Calcular tiempo de resolución promedio de tickets por día
tiempo_resolucion_por_ticket_por_dia = data_resolucion_promedio.resample('D', on='fecha_creacion')['resolve_time_hrs'].mean()

# Mezclar con el DataFrame general
metricas_por_dia = metricas_por_dia.merge(tiempo_resolucion_por_ticket_por_dia, how='left', left_on='dia', right_index=True).rename(columns={'resolve_time_hrs': 'avg_resolve_time_hrs'}).fillna(0)
metricas_por_dia.tail()

           dia  avg_resolve_time_hrs
116 2022-04-29                71.210
117 2022-04-30                 0.000
118 2022-05-01                10.965
119 2022-05-02                 2.835
120 2022-05-03                 0.000

Añadir ahora los usuarios registrados en cada día

In [24]:
# Calcular tiempo de resolución promedio de tickets por día
registrados_por_dia = df_tau.resample('D', on='signup_cohort_date')['id'].count()

# Mezclar con el DataFrame general
metricas_por_dia = metricas_por_dia.merge(registrados_por_dia, how='left', left_on='dia', right_index=True).rename(columns={'id': 'registrados'}).fillna(0)
metricas_por_dia.tail()

           dia  avg_resolve_time_hrs  registrados
116 2022-04-29                71.210           20
117 2022-04-30                 0.000           23
118 2022-05-01                10.965           18
119 2022-05-02                 2.835           10
120 2022-05-03                 0.000            1

### Pasar a G Sheets

In [27]:
sheet = client.open("Business_Health_Dashboard")  #open sheet

#replace sheet_name with the name that corresponds to yours, e.g, it can be sheet1
sheet = sheet.worksheet("data_resolve_time")

In [31]:
sheet.update([metricas_por_dia.columns.values.tolist()] + metricas_por_dia.values.tolist(), value_input_option='USER_ENTERED')

{'spreadsheetId': '1ZKpgLgKOSt-8JuokkfHOcTBAG72ER73-RcE-g7sttJ4',
 'updatedRange': 'data_resolve_time!A1:C122',
 'updatedRows': 122,
 'updatedColumns': 3,
 'updatedCells': 366}